### ISSUE TITLE
Why not store data in .xls or .xlsx file formats

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#123]
05-exporting-data.md starts out with an explanation of why not to store data in Excel default file formats (.xls or .xlsx). It's unclear if learners will know that/whether this also applies to other spreadsheet formats. For example, one of the reasons given is that .xls/x is a proprietary format. Is .odt (or other LibreOffice/OpenOffice formats) "proprietary"? Is it still a bad idea to store your data in these formats?

Also, what is a zipdisk? I'm not sure if this will be a motivating example to learners.

**Comment by zjsteyn** [comment]
Looking at the link 
https://en.wikipedia.org/wiki/OpenDocument the following could be noted:

The open data format is open in the sense that the way that it is structured is open to all to understand. But since it is not a static / consistent format in the way that it is parsed by other software packages it basically has the same pitfalls as .xls .xlsx formats.

A possible to add an additional bullet point:

The same is true for other formats such as open data formats used by LibreOffice / Open Office. These formats are not static and does not get parsed the same way by different software packages

**Comment by ErinBecker** [comment]
Thanks @zjsteyn, this looks great. I'll work on incorporating this information into this module.
