### ISSUE TITLE
ideas for expansion/refining of spreadsheet and R lessons

### ISSUE THREAD

**Issue by DrK-Lo** [datacarpentry/spreadsheet-ecology-lesson#196]
My feedback is based on a workshop where we recently taught the R and SQL lessons from the ecology section. In the interest of time, we skipped over teaching them how to build databases and focused more on dplyr and how to query with SQL.  We wanted to cover long vs. wide data formats with tidyr, but didn’t have time.

I think that in the future, I would add more information to the spreadsheet lesson on how to set up spreadsheets for relational databases.  Then I would focus more on how to build databases with SQL or through R, and then teach how to use dplyr to merge data from different tables. It was at the end of the workshop in the R and SQL lesson before we got to this, and we didn’t really have time to explain how functions like “innerjoin” work.

**Comment by hoytpr** [comment]
Hi @DrK-Lo, thanks very much for your feedback. It looks like your extremely good at working with, and organizing data already, and want to do more. This is completely understandable. Our overall Ecology lesson does in fact move to SQL databases, and this spreadsheet lesson is really basic, and designed for beginners.  Your suggestions are probably excellent for a more advanced workshop. I'm sympathetic and appreciate how you want to expose the learners to more tools!
BUT (no offense intended) as a Biologist who is lousy at coding, (and had to look up (dplyr, tidyr, and innerjoin), the different disciplines speak different languages. This topic is (IMHO) complex enough just because it covers different types of spreadsheet programs. The goal is to get Ecologists (Biologists) to use better formatting when entering their data using spreadsheets (eventually leading into the use of relational databases).  Maybe some other can give more feedback.

**Comment by hoytpr** [comment]
Closing due to existence of other lessons on this topic. Thanks @DrK-Lo !
