### ISSUE TITLE
I.e. vs e.g. 

### ISSUE THREAD

**Issue by tylerjrichards** [datacarpentry/spreadsheet-ecology-lesson#222]
In the 'Storing dates as a single string' within 'Dates as data' subset of the 'spreadsheet-ecology-lesson' lesson, 'i.e.' should be replaced by 'e.g.'

I.e. stands for id est, and e.g. stands for exempli gratia (translates loosely to for example). In this case, an example is given so e.g. is probably more appropriate.

**Comment by hoytpr** [comment]
Thanks @tylerjrichards for being so careful in your examination of the lesson! However, in this case, the "for example" refers to a specific line with specific data. The way the lesson is worded (maybe it was different before?) it says "the date March 24, 2015 17:25:35 would become 20150324172535, where:
YYYY: the full year, **i.e.** 2015". So these are specific data points and YYYY couldn't be anything else. Because _i.e._ stands for _id est_ in Latin (translates to "that is"), this looks to be the correct use of that term. If you disagree, let us know, it's been a long time since I took my four years of Latin. I do wish all these Latin terms AND their abbreviations were italicized however.

**Comment by acorpuz** [comment]
Hello, original author here. The phrase was written as explained by @hoytpr, not sure if it is the correct use as my latin is rusty as well.
I do agree to italicize latin terms.

**Comment by hoytpr** [comment]
We'll work on the italics in the BBQ perhaps. Closing #222
