### ISSUE TITLE
Improve description of statements/clauses

### ISSUE THREAD

**Issue by anneglaser** [datacarpentry/spreadsheet-ecology-lesson#253]
It would be helpful to add a quick description of some of the statements used. Mainly the select statement since I know when I first started I had concerns on if I was changing the underlying data or not. Also the group by, it would be useful to call out that the group by identifier must exist in the select statement.

Description:
SELECT statement can access data in a database and returned specified columns, but it cannot manipulate the data where it lives in the database. However, you can manipulate the data returned to you in your SELECT statement, but it won't save to the database. 

Description:
GROUP BY selection must exist in the select statement.

**Comment by hoytpr** [comment]
Hi @anneglaser and thanks for being a contributor. Honestly , I believe these great comments should go in the SQL lesson, rather than here. The two lessons build off each other, and reference each other, so it's easy to place a contribution in the wrong place. Maybe you should head on over to **https://github.com/datacarpentry/sql-ecology-lesson/issues** to place your comments. If you can do that, and then **close** this issue, it would be great!

**Comment by hoytpr** [comment]
Because @anneglaser has placed these issue comments in  https://github.com/datacarpentry/sql-ecology-lesson/issues, I'm closing this issue. Thanks!
