### ISSUE TITLE
Changing lesson name?

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/spreadsheet-ecology-lesson#262]
This is a somewhat larger conceptual issue, but thought I'd start the discussion. This lesson isn't so much about spreadsheets as it is about how to organize and structure your data in spreadsheets or a tabular format. This is really important because it sets the stage for being able to work with your data in all the other things that we discuss - R, Python, SQL. It's a foundational topic for many reasons, and these good practices aren't usually taught, so it's important people have the opportunity to learn about them, so they can get started with their own data projects. Otherwise it's a roadblock you hit right away.

This idea about whether this lesson is about particular spreadsheets and what concepts and where to start with or how to present this lesson is the subject of a few of the issues.

What about renaming this lesson to something like 'Tidy data' and then doing a few updates (I actually don't think it would be too much) to reflect that focus? It would still include working in the spreadsheet format and how it needs to be structured, but clearer that it's not about a particular spreadsheet program or set of commands.

**Comment by hoytpr** [comment]
@tracykteal I see your point. I agree that anything resembling a spreadsheet should be considered a pre-database collection. From the Life Science perspective it would be best to continue using "spreadsheet(s)" in the title otherwise it won't register with Life Scientists as a way to improve on spreadsheets (which they are going to continue to use). Without giving it a lot of thought, I'd suggest something like "Using tidy data in spreadsheets" (for downstream use).  Or "how to input tidy data to spreadsheets". Even "Best practices for spreadsheet data entry".  "Tidy data practices for spreadsheet usage"

**Comment by tracykteal** [comment]
Good point about keeping 'spreadsheets' in the title. I like all of those title ideas. Also the words 'tidy data' are probably not particularly meaningful if you haven't encountered the term before.

**Comment by hoytpr** [comment]
Then "Best practices for spreadsheet data entry"? I think it's more descriptive. Is this something the CAC should do? It might break a few links from other lessons.

**Comment by hoytpr** [comment]
"Tidy data entry and organization in spreadsheets"?

**Comment by hoytpr** [comment]
Might be addressed in issue #296 and called "spreadsheets-data-organisation-and-management "

Comments welcome.

**Comment by hoytpr** [comment]
Closing this because it seems it would break links in other lessons.
