### ISSUE TITLE
Various lesson improvements in a separate repo

### ISSUE THREAD

**Issue by anenadic** [datacarpentry/spreadsheet-ecology-lesson#296]
We did a copy (rather than a fork) of this lesson at: https://github.com/Southampton-RSG/spreadsheets-data-organisation-and-management. The main modifications include:

- a few screenshots were added to help make this lesson suitable for self-learning and making it easier for learners to follow it on their own
- removed some of the repetitive text and tightened the narrative a bit
- merged in some small bits from the equivalent lesson from Social Sciences curriculum (mainly dates and quality assurance)
- made sure all data files are referred to from the Setup section (which was not the case previously as one data file was introduced in the middle of the lesson). All messy data is not contained in one spreadsheet with 4 tabs and available from the data folder of the repo (as we could not upload it back to Portal Teaching Dataset).

I'd like to invite you to have a look and review this version of the lesson. If you feel that this is something worth merging back into the main lesson, I'd be happy to with you to make a fork that would be suitable for creating a PR.

**Comment by anenadic** [comment]
Tagging @hoytpr as not sure who the current official maintainers of the lesson are.

**Comment by hoytpr** [comment]
Hi @anenadic , I'll take a look.

**Comment by hoytpr** [comment]
Okay, **WOW** you did a great job @anenadic !!!!

I copied your repo to my home computer to render it,
and went through all the lessons. Very impressive!

Setup page was very good. 
Good use of styles (didn't even know 'hearts' were a thing!)
Removed repetitive aspects of setup

**Ep. 01** Solution shortened and actually it improves the flow of the lesson
removing the reference to an R book is probably best. 

You correctly turned "Using Multiple Tables" into an exercise.

### Change suggestion Ep. 01-A

The following might be shortened. I currently use this in a class and emphasize that it's computers that need this data, not humans. I emphasize to think of your file differently because it's not just a data-recording file, it's the entry file to your computational analysis.

> There is no reason why observations from different sites or different years should not go into a single table. You just need to keep track of them by using new columns (in this examples, one for site and one for year). Keeping data from the same experiment in a single table will help you stick to a consistent data structure, and avoid errors when looking up data from different tables.
> 
> Using multiple tables on one page also makes it difficult for humans to keep track of the data - especially if one of the tables is hidden off the edge of the spreadsheet. Multiple tables also increases the risk of using the same column name in multiple places, which will make it significantly harder to clean your data.

### Change suggestion Ep. 01-B
_**I would change:**_
"Whatever the reason, it is a problem if unknown or missing data is recorded as -999, 999, or 0. Statistical programs do not know that these are intended to represent missing (null) values and, because they are valid numbers, they will be included in calculations which will lead to incorrect results. How these values are interpreted will depend on the software you use to analyse your data."
**_TO:_**
"Statistical software will differ on what they interpret as a null value. Make sure you know the correct representation for `null` in your downstream analyses. If uncertain, using blanks, `NA` (used in R), or `NaN` (used in Python) are good options. "

### General comments on Ep. 02:
You did a great job explaining these points, but included a lot of extra text. This is probably okay for a lesson that is mostly discussion, but I liked the "Example" + "Solution" format of the topics. 

### General comments on Ep. 03
You did a great job reformatting this lesson. 
I couldn't find anything to change, and liked very much the link to changing gene names. 

### General comments on Ep. 04
Again, you must have spent a lot of time on this and did a great job. This section
needed updating and it's good that you used examples from a Mac because the Windows 
examples were from mixed versions. 

I also agree that "A Note on Cross-platform Operability" should be eliminated. 
This has bothered me since 2016, and we tried to re-explain it in 2019, but it
is confusing and just isn't an issue anymore. As such, it's a bad way to end the workshop.

-----

It would fantastic for you to work on a PR for this and I would be happy to assist in any way.

If you want to work on your repo at https://southampton-rsg.github.io/spreadsheets-data-organisation-and-management/
before submitting a PR, that would be fine with me too. 

Thanks very much for such hard and careful work!!!

Peter

**Comment by anenadic** [comment]
Hi  @hoytpr! Thank you so much for being so prompt and giving me great feedback. I have been annoyed in the past by some of the same things you mention ;-). I am going to have a look at your comments and try and incorporate them in my repo first. Wrt PR - because I modified the logo and a few other things in config - do you think merging from my repo could be relatively easily done (and easier for me but more work for you potentially) or it would require a separate clean fork with me then copying in all the lessons (more work for me)? I am fine either way, just the speed of things would be affected.

**Comment by anenadic** [comment]
Actually, a new clean fork with me copying in various episodes and bits is probably a better idea - I'd be up for that @hoytpr.

**Comment by hoytpr** [comment]
Of course! You're correct. Thanks again!

Peter

Peter R. Hoyt
Oklahoma State University
Genomics Facility
Stillwater, OK

________________________________

**Comment by anenadic** [comment]
I've just done a PR: https://github.com/datacarpentry/spreadsheet-ecology-lesson/pull/297 @hoytpr. Let me know if I missed anything. 

Wrt your comments on Ep. 01-A and Ep. 01-B - I have incorporated them in the text at various places rather than shortening and replacing my original text. This made the new text longer, which is probably not the desirable effect but I felt that, e.g. explaining why putting -999 as a null value is important to novices who might not understand why this may cause problems. It may be obvious to instructors but if we want this lesson to be used in a self-learning manner than perhaps "more is more". Feel free to cut things out when merging - it is ultimately your call.

**Comment by anenadic** [comment]
Btw. @hoytpr I've done the same thing with the OpenRefine lesson (https://github.com/Southampton-RSG/openrefine-data-cleaning) which was devoid of any screenshots and very hard to pick up by new instructors (let alone novice learners trying to go through it). I have poked one of them (who did the last commit) to do the review but I am not sure who the official maintainers are. If you happen to know them - send them my way :-). Thank you once again for being so prompt!

**Comment by fontikar** [comment]
Hi @anenadic @hoytpr 👋 
@metut and I are the new maintainers for this lesson! 
Thanks for both your contributions, it looks like everything here is all set so we are closing this issue :) 

Feel free to reopen if we are have missed anything!
