### ISSUE TITLE
Suggested edits/updates for 'Quality Control' lesson

### ISSUE THREAD

**Issue by seanboyle106** [datacarpentry/spreadsheet-ecology-lesson#299]
Below are a couple suggestions for updates/edits to the Quality Control lesson (https://datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/index.html).

1. The first sentence in the Conditional Formatting section currently reads as "Conditional formatting basically can do something like color code your values by some criteria or lowest to highest." I think this is somewhat vague, and rather that stating an example of what this tool can do, suggests that its purpose is to do something vaguely similar to this. This could be reworded to read as "Conditional formatting does things like color code your values by some criteria or lowest to highest, as well as other useful tools such as identifying duplicate entries, identifying numbers above or below their average, and identifying numbers within a certain percentile."

2. Consider updating the instructions for Conditional formatting exercise. Currently, instructions seem to be for an older version of excel (i.e., not Office 360). In step 2, the instruction reads "In the main Excel menu bar, click Home > Conditional Formatting... choose a formatting rule.". However, current versions of excel would require learners to 'click Home > Conditional Formatting > New Rule'. The subsequent step could be rewritten as "Step 3. Under Select a Rule Type, select _Format all cells based on their values_ and select any _2-Color Scale_ formatting rule. Choosing any formatting rule may lead to learners choose rules which do not align with the rest of the exercise (i.e., Top/Bottom Rules). See Image below for clarity. The images used in the exercise should be fine to remain. 
 
![Conditional](https://user-images.githubusercontent.com/43148716/103662220-3f1d6f80-4f4a-11eb-8b36-90da6ac53782.png)

---

**Comment by hoytpr** [comment]
Hi @seanboyle106 and thanks for your suggestions! You are correct that some of these images are for older versions of Excel and making this wording (and example) more specific is a great idea. We are going to go through this lesson soon  with potentially significant re-writes and we will keep this suggestion in the issues while considering the new wording.

Thanks!

**Comment by hoytpr** [comment]
Hi again @seanboyle106 and sorry for the delayed response. The bottom line is that the purpose of this lesson is NOT to teach how to use Excel. Conditional formatting is basically something we want to tell people to not do. As for finding duplicates, we want people to learn how to use `sort` and `unique` in the BASH shell instead. This lesson is just to help those people who are dependent on Excel for data recording, to do the very best job the can, so that when exported as a textfile/data frame, it can be read by downstream analyses software. 

I do agree that we can do better than saying "Conditional formatting basically can do something like color code your values by some criteria or lowest to highest." Let me know if you want to re-word this sentence in a PR or I can fix it later this week. 

Thanks again! Don't stop making suggestions! It's the community that makes these lessons work well. 

Pete
