### ISSUE TITLE
Add more of the common mistakes to messy spreadsheet

### ISSUE THREAD

**Issue by dafnevk** [datacarpentry/spreadsheet-ecology-lesson#305]
The messy spreasheet currently contains only a few of the common mistakes explained in Episode 2. I think it would be nice to introduce a few more mistakes, e.g. merging cells, problematic null values, entering more than one piece of information in a cell, using special characters.

This way, the content of episode 2 can be nicely related to the exercise that the learners just did.

**Comment by hoytpr** [comment]
Hi @dafnevk and thanks for the suggestions. You can also see in issue #306 there are requests for more mistakes. I totally get it that there are many more problems with Excel as a data entry sheet. Your input is really important, but let me tell you more about this lesson. First, we are not trying to teach people how to use Excel. Basically we just want to use it as a Data recording device, and only because it's so common. We say at the beginning, we aren't going to do plots or analyses in Excel. We want to help you enter data so that when exported as a text file, it will have the correct format for downstream software. 

As for your suggestions of "merging cells, problematic null values, entering more than one piece of information in a cell, using special characters.", these are great examples. In fact some are already covered in the "messy" spreadsheet. But having taught this many times, it takes too much time to go through all of Excels problems!  IMHO, you go ahead and make mentions of these issues when you teach the course. It not illegal to add a few more examples! Have fun and give as many examples as you have time for. 

So I'm going to close #306 but feel free to comeback here and discuss this more.
