### ISSUE TITLE
Suggestion for adding some more common mistakes

### ISSUE THREAD

**Issue by urjoshi** [datacarpentry/spreadsheet-ecology-lesson#306]
The lesson captures an exhaustive list of possible mistakes committed by users of Excel. In addition, I would like to suggest the inclusion of two more mistakes.

1. Use of formulas within cells is common. A note to users reminding them to insert the = operator after typing a formula would be helpful. Sometimes users may type the formula, but actually forget to insert the = symbol before the operation. For instance, when adding two cells A1 & A2 they may type _A1+A2_ instead of _=A1+A2_. As a result, the output of the formula won't be visible to them. 

2. Secondly, I wanted to bring attention to the fact that sometimes cells may have the default datatype set to _Text_. If the formatting of the cell where a formula is being used, is not changed from _Text_ to _General_, the actual computed value after using a formula may not be reflected in the cell.

**Comment by hoytpr** [comment]
Hi @urjoshi and thanks for the suggestions. Let us go through the new lesson releases and then we can make decisions about this and #305 for this lesson.

**Comment by hoytpr** [comment]
Hi @urjoshi 

I think the best response here is simlar the ones given to issue #305 .

We appreciate your suggestions. You can also see other  issues requesting more examples of more mistakes. There are **many** more problems with Excel as a data entry sheet. Your input is really important, but in this lesson we are not trying to teach people how to use Excel. Basically we just want to use it as a Data recording device, and only because it's so common. We state at the beginning, we aren't going to do plots or analyses in Excel. We want to help you learn how to enter data so that when exported as a text file, it will have the correct format for downstream software.

Thanks again for your suggestions, and feel free to bring up your pet peeve when working with Excel!

-p
