### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [datacarpentry/spreadsheet-ecology-lesson#309]
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by hoytpr** [comment]
I can see where when are going through the Common Spreadsheet Errors, it would be nice to jump back to the list at the top of the page. Is this what you are talking about? Are there other examples?

Thanks!

**Comment by zkamvar** [comment]
Hi @hoytpr, No, this is referring to the links next to headings that you can click on to get the link to that section in the navigation bar. If you hover over https://carpentries.github.io/lesson-example/02-tooling/index.html#repositories-on-github you'll see an example of this.

I'll create a PR right now (though it may take me a few minutes because I have to resolve a lot of conflicts)
