### ISSUE TITLE
Add more interactive material to lesson

### ISSUE THREAD

**Issue by ethanwhite** [datacarpentry/spreadsheet-ecology-lesson#6]
The spreadsheet lesson doesn't have a lot of work for students to do with the instructor. Needs more interactive work, more exercises.

**Comment by apawlik** [comment]
@ethanwhite agree. In fact I have been thinking about a bit of a different approach to the spreadsheet part. Here is what I thought:
1. Based on the material we have, create 1-2 bad spreadsheet containing lots of problems, mistakes and errors.
2. We start the workshop splitting people into groups of 3-4 and ask them to download these spreadsheets.
3. They are given 30 (45?) min to identify as many issues with the spreadsheets as they can and note them down.
4. Once their done, the instructor does a "round" table; looping over the groups - each group says one thing they identified wrong with the spreadsheet until we reach saturation (i.e. all groups told us what their found). 
5. We then show the learners the materials we have and the list of the problems we know were introduced in the spreadsheets (interesting to see how many they identified, whether they used similar terminology etc etc maybe even found new issues).
6. And that's it - we move on to the next module...R. 

I think in this way we make it interesting and engaging for the advanced and beginners. It's also a nice icebreaker.

 @tracykteal @hlapp @karthik @kcranston @gvwilson @ethanwhite - what do you think?

**Comment by kcranston** [comment]
I like the idea of a exercise like this. Is the idea that we would do at the very beginning (prior to any other instruction) or that there would be some introductory material before the exercise? If the former, I would expect that the learners would not pick up on many of the problems, so we would need to go back and revisit, either later in the morning or during the R / spreadsheet lessons (remember this spreadsheet? what would happen if we tried to load that into SQLite?).

**Comment by apawlik** [comment]
I'd start with that without any instruction. I think we could try revisit depending on how many things people picked on. But remember that the idea is that the groups report back and it's likely that most problems will be picked up (it takes 2-3 people in the audience who are pretty experienced with spreadsheets). I may have a skewed experience but both times I taught the spreadsheet module - most people in the audience were aware of the issues. I suppose it would be more engaging for them to try to identify them. 
I think I wasn't very clear on the 5 and 6 in my proposed module workflow: basically the instructor goes in rounds and asks groups what they identified (so in loops "Group 1 - provide 1 problem; Group 2 - provide another problem...Group N - provide a problem; and back Group 1 - problem...." until none of the groups has problems that haven't been already identified). Then the instructor  compares this list concatenated from all the reported problems with the list we have (so that needs to be in the materials, we just don't link the materials explicitly before the workshop "security by obscurity". Anyways, if they find them, no problem. It's an exercise.
So eventually I think almost all problems will be identified.

Hence, this would be the whole spreadsheet module.

Though I like @kcranston idea to revisit that in further module `(remember this spreadsheet? what would happen if we tried to load that into SQLite?).`

**Comment by tracykteal** [comment]
I think we've now constructed the lesson this way. Thanks for all the feedback! We haven't explicitly added the 'remember the messy spreadsheet? what would happen if we tried to load that in to SQL'. That's a good addition. I've filed an issue there to add that to the narrative/instructor notes'. https://github.com/datacarpentry/sql-ecology/issues/50

Think we're OK to close this issue?

**Comment by ethanwhite** [comment]
Yep, awesome work!
