### ISSUE TITLE
Unclear where instructors should start

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheet-ecology-lesson#92]
If I was teaching this lesson, I wouldn't know whether to start with the index.md or 00-intro.md pages. If index.md is considered part of the lesson, instructors should start there and we can get rid of the duplicated information about the topics to be covered on 00-intro.md since these are listed in the schedule already.

Possibly add this info also to the instructor notes.

**Comment by tracykteal** [comment]
I think in general index.md is just meant to be an overview of the full lesson as the default 'home' page for the lesson. It has an overview of the lesson (that introductory text) and the links for Getting Started and For Instructors along with the list of episodes in the lesson. 

I changed 'Prerequisites' to 'Getting Started' and added the 'For Instructors' section, but otherwise it's consistent with the SWC lessons (e.g. http://swcarpentry.github.io/python-novice-inflammation/), so it might be that instructors aren't too confused about where to start. 

It's actually serving three purposes
1. A self-guided learner who just comes to the lesson. This is the landing page.
2. A learner in a workshop. This is where you would point them for the materials that are going to be used in the workshop.
3. An instructor in the workshop. This would be where they would start to see what they were going to teach. That's why I added the 'For instructors' section on the index page. It's not in the default template. 

If it's confusing or not serving these three audiences (which admittedly is a little challenging) we can think about how to restructure.
